### ISSUE TITLE
Snorkel Spark tutorial link broken

### ISSUE THREAD

**Issue by jennxf** [snorkel-team/snorkel#1490]
## Issue description
On https://hazyresearch.github.io/snorkel/blog/snark.html:

link to [Spark-Distributed Labeling Functions Tutorial](https://github.com/snorkel-team/snorkel/blob/master/tutorials/snark/Snark%20Tutorial.ipynb) is broken. 

link to [Crowdsourcing Tutorial](https://github.com/HazyResearch/snorkel/blob/master/tutorials/crowdsourcing/Crowdsourced_Sentiment_Analysis.ipynb) is broken. 

link to [Intro Tutorial](https://github.com/HazyResearch/snorkel/tree/master/tutorials/intro) is broken.

link to [Chemical disease tutorial](https://github.com/snorkel-team/snorkel/tree/master/tutorials/cdr) is also broken.

**Comment by bhancock8** [comment]
Thanks a bunch for bringing this to our attention! It should now be fixed.

**Comment by narayana1043** [comment]
@bhancock8 the links are still broken, Can we please reopen the ticket

**Comment by rbhatia46** [comment]
Hi,
Does anyone have the link to the Spark tutorial?
